name: build-and-deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH=$HOME/.yarn/bin:$PATH

      - name: Install dependencies and build packages
        run: yarn run init

      - name: Lint packages
        run: |
          yarn run lint
          yarn run type-check

      - name: Run unit tests
        run: yarn run test

      - name: Get branch name
        id: get_branch_name
        run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF/refs\/heads\//}

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Log branch name and tag
        run: |
          echo "Branch name is ${{ steps.get_branch_name.outputs.BRANCH_NAME }}"
          echo "Tag is ${{ steps.get_tag.outputs.TAG }}"

      - name: Publish packages
        if: steps.get_branch_name.outputs.BRANCH_NAME == 'master' && steps.get_tag.outputs.TAG != ''
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=\$env:NPM_AUTH_TOKEN" >> .npmrc
          yarn run publish-lerna-cutoff