name: Build and publish

on:
  push:
    branches:
      - main
    tags:
      - v**
  pull_request:
    branches:
      - main

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-and-publish:
    uses: badbatch/repodog/.github/workflows/master-build-and-publish.yml@main
    secrets:
      npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}
