name: Build and publish

on:
  push:
    branches:
      - main
    tags:
      - v**
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    permissions:
      id-token: write
      contents: read
    uses: badbatch/repodog/.github/workflows/master-build-and-publish.yml@main
